language: cpp
compiler: gcc
sudo: required
install: true
script:
  - ./build.sh
  - cd build/test/
  - ./run_all_test.sh
  - cd ../python_package/test/test/
  - python test_python.py test_data_conversion.py
